### ISSUE TITLE
There doesn't seem to be a change to the registry

### ISSUE THREAD

**Issue by stephen147** [PaulaScholz/RegistryUWP#1]
Thanks for this.

I have checked `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Run` and there's no update to the registry and also `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`

Is it changed or is it a virtualised registry item?

It does however add it to the startup list when I use the task manager.

I've also had a look with [Autoruns](https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns) but there's no entry there either for notepad.exe.

**Comment by PaulaScholz** [comment]
The registry will only change on 64-bit Windows when called from a 64-bit process.
