### ISSUE TITLE
Problems when building the package

### ISSUE THREAD

**Issue by stephen147** [PaulaScholz/RegistryUWP#2]
When I open the solution in VS 2019 and press F5 I get these warnings.

![image](https://user-images.githubusercontent.com/14054664/143600751-3345b1b6-dcdb-480b-b591-6a72c70a3093.png)

```
The type or namespace name   'ApplicationModel' does not exist in the namespace 'Windows' (are you missing   an assembly reference?)
The type or namespace name   'AppServiceClosedEventArgs' could not be found (are you missing a using   directive or an assembly reference?)
The type or namespace name   'AppServiceConnection' could not be found (are you missing a using directive   or an assembly reference?)
The type or namespace name   'AppServiceConnection' could not be found (are you missing a using directive   or an assembly reference?)
The type or namespace name   'AppServiceConnection' could not be found (are you missing a using directive   or an assembly reference?)
The type or namespace name   'AppServiceRequestReceivedEventArgs' could not be found (are you missing a   using directive or an assembly reference?)
The type or namespace name 'Collections'   does not exist in the namespace 'Windows.Foundation' (are you missing an   assembly reference?)
There was a mismatch between the   processor architecture of the project being built "MSIL" and the   processor architecture of the reference "W:\SS_CODING\Visual Studio   Projects\VS2019\RegistryUWP-master\RegistryUWP\bin\x86\Debug\RegistryUWP.exe",   "x86". This mismatch may cause runtime failures. Please consider   changing the targeted processor architecture of your project through the   Configuration Manager so as to align the processor architectures between your   project and references, or take a dependency on references with a processor   architecture that matches the targeted processor architecture of your   project.
```

So it's these that are missing and also I get the mismatch between the processor architecture error.
```
ApplicationModel
AppServiceClosedEventArgs
AppServiceConnection
AppServiceRequestReceivedEventArgs
Collections
```

What do I need to do to fix this? Thanks.

**Comment by PaulaScholz** [comment]
This will only work on 64-bit Windows.

**Comment by stephen147** [comment]
That's what I'm using.

**Comment by PaulaScholz** [comment]
Please describe your OS and Visual Studio toolchain.

**Comment by stephen147** [comment]
Windows 10 Pro (Build 19044)

Not sure what you mean by the VS toolchain.

**Comment by PaulaScholz** [comment]
I meant what version of Visual Studio do you use, but the error message says 2019.

> "There was a mismatch between the   processor architecture of the project being built "MSIL" and the   processor architecture of the reference "W:\SS_CODING\Visual Studio   Projects\VS2019\RegistryUWP-master\RegistryUWP\bin\x86\Debug\RegistryUWP.exe",   "x86". This mismatch may cause runtime failures. Please consider   changing the targeted processor architecture of your project through the   Configuration Manager so as to align the processor architectures between your   project and references, or take a dependency on references with a processor   architecture that matches the targeted processor architecture of your   project."

Have you tried going through the Configuration Manager and ensuring that all your projects target x64?

**Comment by stephen147** [comment]
I had that in the first post. It's the community edition if that makes a difference.

Tried that and still, the same issue. Never mind I wrote my own in the meantime. I was just trying to use this as an example.
